package com.mobilemocap.ahmadriza.apik.WorkoutAndExercise.Database;

import android.content.ContentValues;
import android.content.Context;
import android.database.SQLException;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

public class DatabaseHelper extends SQLiteOpenHelper {
    private static final String SQLiteDatabaseName = "todo.db1001";
    private static DatabaseHelper instance = null;
    public static String table;
    public static final String[] exerciseCategoryNames = {"Abdominal", "Chest", "Biceps", "Shoulders", "Triceps", "Legs", "Back", "Traps", "Cardio"};
    public static final String[] workoutCategoryNames = {"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"};
    private String[] mealCategoryNames = {"MondayMeals", "TuesdayMeals", "WednesdayMeals", "ThursdayMeals", "FridayMeals", "SaturdayMeals", "SundayMeals"};

    public static DatabaseHelper getInstance(Context context) {
        if (instance == null) {
            instance = new DatabaseHelper(context);
        }
        return instance;
    }

    //Initialise database connection
    private DatabaseHelper(Context context) {
        super(context, SQLiteDatabaseName, null, 1);
    }

    //Create database tables (exercise, workout, diet)
    @Override
    public void onCreate(SQLiteDatabase db) {
        try {
            for (String exerciseCategoryName : exerciseCategoryNames) {
                table = exerciseCategoryName;
                db.execSQL(
                        "CREATE TABLE IF NOT EXISTS " + DatabaseHelper.table + " (" +
                                "_id INTEGER PRIMARY KEY AUTOINCREMENT," +
                                "exercise_name TEXT NOT NULL," +
                                "number_of_sets INTEGER NOT NULL," +
                                "reps_per_set INTEGER NOT NULL," +
                                "estimate_time INTEGER NOT NULL," +
                                "description TEXT NOT NULL" +
                                ")"
                );
            }

            for (String workoutCategoryName : workoutCategoryNames) {
                table = workoutCategoryName;
                db.execSQL(
                        "CREATE TABLE IF NOT EXISTS " + DatabaseHelper.table + " (" +
                                "_id INTEGER PRIMARY KEY AUTOINCREMENT," +
                                "workout_routine_name TEXT NOT NULL," +
                                "exercise_name TEXT NOT NULL," +
                                "number_of_sets INTEGER NOT NULL," +
                                "reps_per_set INTEGER NOT NULL," +
                                "estimate_time INTEGER NOT NULL," +
                                "description TEXT NOT NULL" +
                                ")"
                );
            }

            for (String mealCategoryName : mealCategoryNames) {
                table = mealCategoryName;
                db.execSQL(
                        "CREATE TABLE IF NOT EXISTS " + DatabaseHelper.table + " (" +
                                "_id INTEGER PRIMARY KEY AUTOINCREMENT," +
                                "meal_category_name TEXT NOT NULL," +
                                "meal_name TEXT NOT NULL," +
                                "proteins INTEGER NOT NULL," +
                                "carbs INTEGER NOT NULL," +
                                "fats INTEGER NOT NULL," +
                                "calories INTEGER NOT NULL," +
                                "description TEXT NOT NULL" +
                                ")"
                );
            }

            populateTables(db);
        } catch (SQLException e) {
            Log.d("SQL exception caught in: ", "DatabaseHelper onCreate method");
        }
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
    }

    public void populateTables(SQLiteDatabase db) {
        //Create exercises
        ContentValues newItem = new ContentValues();
        newItem.put("exercise_name", "Ab Wheel Rollout");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 40);
        newItem.put("description", "Kneel on the floor and hold an ab wheel beneath your shoulders. Brace your abs and roll the wheel forward until you feel you’re about to lose tension in your core and your hips might sag. Roll yourself back to start.");
        db.insertOrThrow("Abdominal", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Arms-High Partial Situp");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 40);
        newItem.put("description", "Lie on your back, knees bent at 90 degrees, and raise your arms straight overhead, keeping them pointing up throughout the exercise. Sit up halfway, then steadily return to the floor.");
        db.insertOrThrow("Abdominal", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Barbell Rollout");
        newItem.put("number_of_sets", 2);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Load the bar with 10-pound plates and kneel on the floor behind it. Your shoulders should be over the bar. Brace your abs and roll the bar forward, reaching in front of you until you feel your hips are about to sag. Roll yourself back.");
        db.insertOrThrow("Abdominal", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Barbell Russian Twist");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Grasp the bar near the very end again—this time with both hands. Stand with feet at shoulder width. Swing the bar to your left, pivoting your feet as needed, then swing to your right.");
        db.insertOrThrow("Abdominal", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Swiss Ball Crunch");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Lie back on the ball with feet shoulder-width apart on the floor. Your lower back should be supported by the ball. Place your hands behind your ears and tuck your chin. Curl your body up off the ball until you’re sitting up.");
        db.insertOrThrow("Abdominal", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Dip/Leg Raise Combo");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Suspend yourself over the parallel bars at a dip station. Bend your knees slightly and raise your legs in front of you until they’re parallel to the floor. This will build you a magazine-worthy six-pack.");
        db.insertOrThrow("Abdominal", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Flutter Kick");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 50);
        newItem.put("description", "Lie on your back with legs straight and arms extend out at your sides. Lift your heels about 6 inches off the floor and rapidly kick your feet up and down in a quick, scissor-like motion.");
        db.insertOrThrow("Abdominal", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Horizontal Cable Woodchop");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 40);
        newItem.put("description", "Set an adjustable cable pulley to shoulder level (or attach a band to a sturdy object) and grasp the handle with both hands. Stand with feet shoulder width apart, perpendicular to the anchor point, and arms extended, far enough away from the machine so there’s tension on the cable. Twist away from the machine as if you were chopping into a tree. Keep your feet stationary.");
        db.insertOrThrow("Abdominal", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Leg Raise");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Lie on the floor and hold onto a bench or the legs of a heavy chair for support. Keep your legs straight and raise them up until they’re vertical. Lower back down, but stop just short of the floor to keep tension on your abs before the next rep.");
        db.insertOrThrow("Abdominal", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Ball Russian Twist");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 40);
        newItem.put("description", "Sit on the floor in the top position of a situp and, holding a medicine ball with both hands, extend your arms in front of you. Explosively twist your body to one side and then twist back. Alternate sides.");
        db.insertOrThrow("Abdominal", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Plank");
        newItem.put("number_of_sets", 1);
        newItem.put("reps_per_set", 2);
        newItem.put("estimate_time", 120);
        newItem.put("description", "Get into pushup position and bend your elbows to lower your forearms to the floor. Hold the position with abs braced.");
        db.insertOrThrow("Abdominal", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Pullup to Knee Raise");
        newItem.put("number_of_sets", 2);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Hang from a pullup bar with hands outside shoulder width and palms facing away from you. Pull yourself up until your chin is over the bar and then raise your knees to your chest in the top position.");
        db.insertOrThrow("Abdominal", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Side Plank");
        newItem.put("number_of_sets", 1);
        newItem.put("reps_per_set", 1);
        newItem.put("estimate_time", 120);
        newItem.put("description", "Lie on your left side resting your left forearm on the floor for support. Raise your hips up so your body forms a straight line and brace your abs—your weight should be on your left forearm and the edge of your left foot. Hold the position with abs braced.");
        db.insertOrThrow("Abdominal", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Situp and throw");
        newItem.put("number_of_sets", 2);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Hold a medicine ball with both hands in front of your chest and sit on the floor. Anchor your feet under something sturdy for support, and lie back on the floor a few feet away from a brick or concrete wall. Explosively sit up and throw the ball into the wall and then catch it on the rebound. If you have a partner, you can throw the ball to him/her instead.");
        db.insertOrThrow("Abdominal", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Barbell Bench Press");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 40);
        newItem.put("description", "Grasp the bar just outside shoulder-width and arch your back so there’s space between your lower back and the bench. Pull the bar out of the rack and lower it to your sternum, tucking your elbows about 45° to your sides. When the bar touches your body, drive your feet hard into the floor and press the bar back up.");
        db.insertOrThrow("Chest", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Dumbbell Bench Press");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 50);
        newItem.put("description", "Lie back on a flat bench with a dumbbell in each hand. Hold the weights at shoulder-level, then press the weights straight up.");
        db.insertOrThrow("Chest", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Incline Dumbbell Flye");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 40);
        newItem.put("description", "Set an adjustable bench to a 30°-45° angle, and lie back on it with a dumbbell in each hand. Turn your wrists so your palms face each other. Press the weights straight over your chest, then, keeping a slight bend in your elbows, spread your arms open as if you were going for a big bear hug. Lower your arms until you feel a stretch in your pecs, then bring the weights back together over your chest.");
        db.insertOrThrow("Chest", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Cable Crossover");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Stand between two facing cable stations with both pulleys set midway between the top and bottom of the station. Attach a D-handle to each pulley and hold one in each hand. Keep your elbows slightly bent, and step forward so there’s tension on the cables. Flex your pecs as you bring your hands together out in front of your chest. Alternate stretching and flexing after each set.");
        db.insertOrThrow("Chest", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Incline Dumbbell Press");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Set an adjustable bench to a 30°-45° angle and lie back on it with a dumbbell in each hand at shoulder-level. Press the weights over your chest.");
        db.insertOrThrow("Chest", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Chest Press Machine");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Load plates on both sides of a flat-press machine, and adjust the seat so that both of your feet are flat on the floor. Grasp the handles and press to a full lockout.");
        db.insertOrThrow("Chest", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Dumbbell Flye");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Lie back on a flat bench with a dumbbell in each hand. Keep a slight bend in your elbows and spread your arms wide, lowering the weights until they’re even with your chest. Flex your pecs and lift the weights back to the starting position.");
        db.insertOrThrow("Chest", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Pullover");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Lie on your back on the floor and hold one dumbbell overhead with both hands. Press the weight over your chest, then reach back over your head, bending your elbows only slightly. Continue until you feel a stretch in your lats, then pull the dumbbell back over your chest. Take a deep breath every time you lower the dumbbell behind you.");
        db.insertOrThrow("Chest", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Pushup");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 15);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Get into pushup position with hands under your shoulders. Your entire body should be straight and your core braced. Lower your body, keeping your elbows tucked near your torso and your head neutral, until your chest is almost touching the floor. Fire your chest and triceps and raise your body back to pushup position.");
        db.insertOrThrow("Chest", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Close-Grip Pushup");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Perform these as you would normal pushups, but position your hands close together. The closer together your hands are, the more this exercise emphasizes the triceps.");
        db.insertOrThrow("Chest", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Band-Resisted Flye");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Attach a band to a sturdy object at shoulder height and repeat with another adjacent to it. Alternatively, tie two bands together and anchor them at the same point behind you. Hold the opposite ends of the bands in each hand and step forward so that your arms are drawn back 90 degrees to your sides and you feel a stretch in your pecs. Keeping your elbows slightly bent, bring your hands together in front of your chest as if you were giving someone a bear hug.");
        db.insertOrThrow("Chest", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Wide-Grip Dips");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 8);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Keeping your arms straight, hold your body up on two parallel bars that are a couple inches wider than shoulder-width apart. Descend until your chest is roughly in line with your hands, then push back up to the starting position, locking out your elbows. Descend while keeping your torso slightly horizontal to the ground, which emphasizes the chest muscles over your triceps.");
        db.insertOrThrow("Chest", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Hammer Curl");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 40);
        newItem.put("description", "Select two dumbbells, and wrap towels around each handle to thicken it. Another option is to use rubber-grip sleeves like Fat Gripz or Grip4orce. Keeping your upper arms stationary at your sides and your palms facing up, curl the weights.");
        db.insertOrThrow("Biceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Behind-the-Back Cable Curl");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Attach a D-handle to the low pulley of a cable machine, grasp the handle in your left hand, and step forward (away from the machine) until there's tension on the cable and your arm is drawn slightly behind your body. Stagger your feet so your right leg is in front. Curl the handle but don't allow your elbow to point forward. Alternate sides.");
        db.insertOrThrow("Biceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "EZ-Bar Preacher Curl");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Sit at a preacher bench, and adjust the bench height so your armpits touch the top of the bench. Grasp an EZ-curl bar overhand at shoulder-width. Curl it up, keeping the backs of your arms against the bench. Take three seconds to lower the bar back down, flexing your triceps as you do it (as if you were performing a cable pushdown).");
        db.insertOrThrow("Biceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Reverse Curl");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Grasp the bar overhand (aka prone grip) at whatever width is comfortable. Keeping your upper arms against your sides, curl the bar.");
        db.insertOrThrow("Biceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Wide-Grip Curl");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Grasp the bar with hands wider than shoulder-width—if you’re using an Olympic bar, your pinkies should be on the outside knurling. Perform curls.");
        db.insertOrThrow("Biceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Close-Grip Curl");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Curl with your hands inside shoulder-width, in the middle of the bar.");
        db.insertOrThrow("Biceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Conventional Barbell Curl");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "You've certainly done this exercise before, but there are plenty of ways to shake up the set/rep scheme. Try this: Place three 5-lb plates on each side of the bar, hands at shoulder-width, and perform 20 reps. That’s one set. Then take off one plate from each side. Perform 30 reps. Unload another plate from each side and do 40 reps. Finally, remove the last set of plates, and do 50 reps with just the empty bar.");
        db.insertOrThrow("Biceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Dumbbell Curl");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Stand holding a dumbbell in each hand with palms facing your sides. Keep your weight on your heels and lean forward slightly. Without letting your upper arms drift forward, curl the weights, rotating your wrists outward so that your palms face you in the top position. Hold the top for a moment and squeeze your biceps. Lower the weights back down and flex your triceps hard in the bottom position (your arms should end up slightly behind your body).");
        db.insertOrThrow("Biceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Barbell Overhead Press");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Set the bar up in a squat rack or cage, and grasp it just outside shoulder width. Take the bar off the rack and hold it at shoulder level with your forearms perpendicular to the floor. Squeeze the bar and brace your abs. Press the bar overhead, pushing your head forward and shrugging your traps as the bar passes your face.");
        db.insertOrThrow("Shoulders", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Standing Dumbbell Fly");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Hold a dumbbell in each hand by your sides. Without shrugging, use your upper body to swing the weights up a few inches. Your arms and torso will form an upside down V shape. Think of it as a lateral raise with momentum but without full range of motion.");
        db.insertOrThrow("Shoulders", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Face Pull");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 40);
        newItem.put("description", "Attach a rope handle to the top pulley of a cable station. Grasp an end in each hand with palms facing each other. Step back to place tension on the cable. Pull the handles to your forehead so your palms face your ears and your upper back is fully contracted.");
        db.insertOrThrow("Shoulders", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "High Pull");
        newItem.put("number_of_sets", 2);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Grasp the bar with hands about double shoulder width and hold it in front of your thighs. Bend your knees and hips so the bar hangs just above your knees. Explosively extend your hips as if jumping and pull the bar up to shoulder level with elbows wide apart, as in an upright row.");
        db.insertOrThrow("Shoulders", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Clean and Press");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Stand with feet shoulder width. Keeping your lower back arched, bend your hips back to lower your torso and grasp the bar with hands shoulder width. Extend your hips to lift the bar off the floor. When it gets past your knees, jump and shrug the bar so that momentum raises it and you catch it at shoulder level. Brace your abs and stand tall. Press the bar straight overhead.");
        db.insertOrThrow("Shoulders", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Band Lateral Raise");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Step on the free end of each band with the opposite foot so the bands form an X in front of your body. Raise your arms 90 degrees out to the sides until your upper arms are parallel to the floor.");
        db.insertOrThrow("Shoulders", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Dip");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Rest the palms of your hands on a bench or chair, and, if available, place your heels on another elevated object in front of you so your legs are suspended. Lower your body until your upper arms are parallel to the floor.");
        db.insertOrThrow("Shoulders", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Dumbbell Overhead Press");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Hold a dumbbell in each hand at shoulder level with palms facing each other and elbows pointing forward. Brace your core and press the weights straight overhead. At the top, shrug your shoulders and hold for a second.");
        db.insertOrThrow("Shoulders", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Snatch-Grip Shrug Pull");
        newItem.put("number_of_sets", 2);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "This is done the same as the low-pull, but keep your elbows straight and perform an explosive shrug once the bar passes your knees.");
        db.insertOrThrow("Shoulders", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Dumbbell Bent-Over Lateral Raise");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Hold a dumbbell in each hand and, keeping your lower back in its natural arch, bend your hips back until your torso is about parallel to the floor. Allow your arms to hang. Now squeeze your shoulder blades together and raise your arms out 90 degrees, with thumbs pointing up, until your upper arms are parallel to the floor.");
        db.insertOrThrow("Shoulders", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", " Incline Bench Press");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Set an adjustable bench to a 30- to 45-degree angle and lie back on it. Grasp the bar just outside shoulder width, arch your back, and pull it off the rack. Lower the bar to the upper part of your chest and then drive your feet into the floor as you press it back up.");
        db.insertOrThrow("Shoulders", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Machine Shoulder Press");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Adjust the seat of a shoulder press machine so that the handles are at shoulder level. If you have shoulder problems, and if your machine allows it, grasp the handles so your palms face each other. Otherwise, grasp them with palms facing forward as normal. Make sure your elbows track in a normal pressing path as you press the handles overhead.");
        db.insertOrThrow("Shoulders", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Bent-Over Reverse Flye");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Set up as you did for the neutral-grip row but with lighter dumbbells. Raise your arms out to your sides 90 degrees, squeezing your shoulder blades together at the top for a second. Complete your set and then rest until the end of three minutes, when your timer goes off.");
        db.insertOrThrow("Shoulders", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Close-Grip Bench Press");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Grasp the bar with your index fingers on the inside edge of the knurling (the rough part of the bar). Arch your back so there’s space between your lower back and the bench. Pull the bar off the rack and lower it to your sternum, tucking your elbows about 45° to your sides. When the bar touches your body, drive your feet hard into the floor and press the bar back up. On your last set, use half the weight and perform as many reps as possible.");
        db.insertOrThrow("Triceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Decline Triceps Extension");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Set an adjustable bench to a slight decline (around 30°), and lie on it with a dumbbell in each hand. Hold the weights over your chest, palms facing each other. Bend your elbows and lower the weights to the sides of your head. Choose a weight you can do 12 reps with on the first set, and use it for every set.");
        db.insertOrThrow("Triceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Band Pushdown");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Attach an elastic exercise band (we like the eFs Pro light bands) to a sturdy overhead object and grasp each side of the loop. Keeping your elbows tight against your sides, extend your arms downward. You can perform a pushdown on a cable machine instead if you prefer.");
        db.insertOrThrow("Triceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Lying Triceps Extension");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Press the bar over your chest, then let your upper arms drift back to about a 45° angle. Bend your elbows to lower the bar behind your head, then extend them to return to the starting position. Keep your elbows in line with your wrists throughout.");
        db.insertOrThrow("Triceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Pullover");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Hold the bar overhead with an overhand, shoulder-width grip, and lie back on the floor. Press the bar over your head, then reach back over your head, bending your elbows only slightly. Continue until you feel a stretch in your lats, then pull the bar back over your chest, flexing your triceps as you go. Focus your mind on your triceps, and you’ll feel them engage more throughout the exercise.");
        db.insertOrThrow("Triceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "One-Erm Overhead Extension");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Hold one dumbbell, and raise your arm behind your head with your elbow bent. Extend your elbow to point your arm straight overhead.");
        db.insertOrThrow("Triceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Dip");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Use dip bars if available, or place your palms on a bench or chair, and extend your legs in front of you. Lower your body until your upper arms are parallel to the floor but no lower. Extend your elbows to come up.");
        db.insertOrThrow("Triceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Close-Grip Pushup");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Get into pushup position with your hands inside shoulder-width. Keeping your abs braced, lower your body until your chest is just above the floor, then push up. For an advanced workout, use the band for resistance by wrapping it around your back and holding an end in each hand.");
        db.insertOrThrow("Triceps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Front Squat");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Set a barbell on a power rack at about shoulder height. Grab the power with an overhand grip at shoulder width and raise your elbows until your upper arms are parallel to the floor. Take the bar out of the rack and let it rest on your fingertips. Your elbows should be all the way up throughout the movement. Step back and set your feet at shoulder width with toes turned out slightly. Squat as low as you can without losing the arch in your lower back.");
        db.insertOrThrow("Legs", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Bulgarian Split Squat");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Stand lunge-length in front of a bench. Hold a dumbbell in each hand and rest the top of your left foot on the bench behind you. Lower your body until your rear knee nearly touches the floor and your front thigh is parallel to the floor. Single-leg training can yield serious strength gains. ");
        db.insertOrThrow("Legs", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Deadlift");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Stand straight up with feet hip-width apart and shins one inch away from the bar. Grip the bar with a double pronated or reverse grip, bend knees and push them into your straight arms. Bring your chest up as much as possible and look straight ahead. Keeping your back flat, extend your hips to stand up, pulling the bar up along your legs to lockout. Here are 4 ways to break your deadlift record.");
        db.insertOrThrow("Legs", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Squat");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "In a squat rack or cage, grasp the bar as far apart as is comfortable and step under it. Place it on your lower traps, squeeze your shoulder blades together, push your elbows up and nudge the bar out of the rack. Take a step or two back and stand with your feet at shoulder width and your toes turned slightly out. Take a deep breath and bend your hips back, then bend your knees to lower your body as far as you can without losing the arch in your lower back. Push your knees out as you descend. Drive vertically with your hips to come back up, continuing to push your knees out.");
        db.insertOrThrow("Legs", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Dumbbell Stepup");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Stand behind a bench or another elevated surface that will put your thigh at parallel to the floor when you step your foot onto it. Hold a dumbbell in each hand and step onto the bench, but leave your trailing leg hanging off.");
        db.insertOrThrow("Legs", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Leg Press");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Adjust the seat of the machine so that you can sit comfortably with your hips beneath your knees and your knees in line with your feet. Remove the safeties and lower your knees toward your chest until they’re bent 90 degrees and then press back up. Be careful not to go too low or you risk your lower back coming off the seat (which can cause injury).");
        db.insertOrThrow("Legs", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Walking Lunge");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Stand with your feet hip width, holding a dumbbell in each hand. Step forward with one leg and lower your body until your rear knee nearly touches the floor and your front thigh is parallel to the floor. Step forward with your rear leg to perform the next rep.");
        db.insertOrThrow("Legs", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Dumbbell Squat");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Hold the weights at shoulder level and stand with feet shoulder-width apart and toes turned slightly out. Squat down as low as you can without losing the arch in your lower back.");
        db.insertOrThrow("Legs", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Barbell Calf Raise");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Place a block, step, or weight plate on the floor. Grasp a barbell and hold it on the backs of your shoulders, as in a squat. Place your toes on the block so your calves are stretched, but make sure you can maintain balance. Raise your heels to come up onto the balls of your feet.");
        db.insertOrThrow("Legs", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Barbell Hip Thrust");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Rest your upper back on a bench and sit on the floor with legs extended. Roll a loaded barbell up your thighs until the bar sits on your lap (you may want to place a towel or mat on your hips or attach a pad to the bar for comfort). Brace your abs and drive your heels into the floor to extend your hips, raising them until your thighs and upper body are parallel to the floor.");
        db.insertOrThrow("Legs", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Seated Calf Raise");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Use a seated calf raise machine, or sit on a bench and rest the balls of your feet on a block or step (and hold dumbbells on your thighs for resistance). Perform a calf raise as described at left, but with hips and knees bent 90 degrees.");
        db.insertOrThrow("Legs", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Deadlift");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Stand with feet hip-width apart and bend your hips back. Your grip should be just outside of your knees. Keeping a flat black, extend your hips to stand up, and pull the bar up along your body until lock-out, as your hips drive through and your shoulders move back. While pulling, keep your eyes on the ground a few feet in front of you. Carefully lower the bar back to the starting position.");
        db.insertOrThrow("Back", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Weighted Pullup");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 8);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Attach a weighted belt to your waist, hold a dumbbell between your feet, or—if you can’t complete your reps with weight—use body weight alone. Hang from a pullup bar with your hands just outside shoulder width. Pull yourself up until your chin is over the bar.");
        db.insertOrThrow("Back", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Dumbbell Romanian Deadlift");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Grasp two dumbbells and hold them with feet set hip-width apart. Keeping your lower back in its natural arch, bend hips back, your torso forward, and lower yourself until you feel a stretch in your hamstrings. You may bend at the knees. Squeeze your glutes at the top of the movement after coming back up.");
        db.insertOrThrow("Back", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Incline Dumbbell Row");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Set an adjustable bench to a 30- to 45-degree incline and lie on it chest-down. Grasp a dumbbell in each hand and draw your shoulder blades back and together as you row the weights to your sides");
        db.insertOrThrow("Back", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Chinup");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Hang from a chinup bar with hands shoulder-width apart using a supinated grip (so, palms facing you). From the bottom of the movement, pull yourself up until your chin is over the bar.");
        db.insertOrThrow("Back", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Trap-Bar Deadlift");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Use a trap bar and stand with feet at hip-width apart. Bend your hips back and grasp the handles. Keeping your lower back in its natural arch, drive through your heels to stand up straight and extend your hips and knees.");
        db.insertOrThrow("Back", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Inverted Row");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Set a barbell in a power rack (or use a Smith machine) at about hip height. (About four rungs up should work). Lie underneath it and grab it with hands about shoulder-width apart with the bottom of your heels on floor. Hang from the bar so your body forms a straight line. Squeeze your shoulder blades together and pull yourself up until your back is fully contracted.");
        db.insertOrThrow("Back", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Towel Cable Row");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Hook a towel to a cable pulley and stand in front of it. Set up to do a row, holding an end of the towel in each hand. Squeeze your shoulder blades together and row the towel to your rib cage.");
        db.insertOrThrow("Back", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Rotational Inverted Row");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "You’ll need a suspension trainer for this exercise. Hold the handles and lean back with arms extended so that your body is supported by the suspension trainer and only your feet are on the floor. Brace your core and hold your body in a straight line. (The lower you set the handles, the harder the exercise; you can elevate your feet to make it even harder.) Start with your palms facing your feet, and as you row your body up, twist your wrists outward so that your palms face up in the top position");
        db.insertOrThrow("Back", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Seated Cable Row");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Attach a straight or lat-pulldown bar to the pulley of a seated row station. Sit on the bench (or floor) with your feet against the foot plate and knees slightly bent. Keeping your lower back flat, bend forward at the hips to grasp the bar and row it to your sternum, squeezing your shoulder blades together in the end position. Extend your arms and feel the stretch in your back before beginning the next rep.");
        db.insertOrThrow("Back", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Yates Row");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Hold the bar with an underhand grip at shoulder-width. Keeping your lower back in its natural arch, bend your hips back and lower your torso to about 60 degrees. Row the weight to your belly button using a slight cheat (use momentum to begin each rep), but don’t let your lower back round. If you have wrist straps, you may use them to help your grip.");
        db.insertOrThrow("Back", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Dumbbell Farmer’s Walk");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Choose a total load that’s equivalent or greater than your body weight. Hold a dumbbell in either hand, and walk quickly yet smoothly with them for 50-100 yards.");
        db.insertOrThrow("Traps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Heavy Barbell Shrug ");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Load up a barbell with the heaviest load you can handle. Focus on staying tall and maintaining an upright posture while you hold the barbell with an overhand grip and shrug your shoulders straight up and down, not forward or back. At the top of the shrug, when you’re in the contracted position, pause for several seconds. Don’t let your shoulders round over or your head protrude forward; your head should remain rigid throughout the entire exercise.");
        db.insertOrThrow("Traps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Deadlift");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Stand with your feet hip-width apart. Bend your hips back to lower your hands and grip the bar's handles in the middle. Your lower back should be flat. Inhale and engage your abs. Stick your chest out and look in front of you, not at the ground. Drive your heels into the floor as you begin lifting the bar. Stand up, squeezing your glutes as you lock out your hips.");
        db.insertOrThrow("Traps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Push Press");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "To perform this movement effectively you’ll either start by cleaning the weight to your upper chest and shoulders, or you can unrack the barbell from a power rack, Seedman says. From there, move into a partial squat by slightly dipping at the knees, then forcefully driving the weight overhead in one swift motion. Once you lock the weight out overhead, pause in the top position for several seconds to gain complete control of the weight. ");
        db.insertOrThrow("Traps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Rows, Pullups, Chinups, or Pulldowns");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Include both a row and a pullup/pulldown movement in all of your trap workouts to target the various upper back muscles from different angles and positions. For all of these moves, pause in both the stretched and contracted positions. These pauses and isometric contractions allow you to squeeze and engage all the muscles of your upper back, lats, and targeted trap regions, Seedman explains.");
        db.insertOrThrow("Traps", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Running");
        newItem.put("number_of_sets", 1);
        newItem.put("reps_per_set", 1);
        newItem.put("estimate_time", 600);
        newItem.put("description", "Running at a steady, moderate pace is a sure way to burn fat and calories, but it’s not the most economical way to build or even maintain muscle.");
        db.insertOrThrow("Cardio", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Stair Climber");
        newItem.put("number_of_sets", 1);
        newItem.put("reps_per_set", 1);
        newItem.put("estimate_time", 600);
        newItem.put("description", "A stair climber offers another popular way to burn fat and calories, but only about 500-600 calories for an 180-lb. man at a moderate pace. “Because of the higher leg lift involved, climbing stairs uses significantly more muscles than just walking—strengthening your legs in a functional way,” says Adams. The primary drawback: Stair climbers can put a lot of weight and pressure on your joints, so it can be difficult for people with bad knees.");
        db.insertOrThrow("Cardio", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Jumping Rope");
        newItem.put("number_of_sets", 2);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "It is cheap, easy to do, increases foot speed, and burns a ton of calories. Think of your favorite boxers, wrestlers, and fighters—they all jump rope. “Jumping rope not only enhances your footwork, shoulder strength, and coordination, but also simulates sprinting, allowing you to burn as much as 500 calories in just 30 minutes");
        db.insertOrThrow("Cardio", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Cycling");
        newItem.put("number_of_sets", 1);
        newItem.put("reps_per_set", 1);
        newItem.put("estimate_time", 600);
        newItem.put("description", "Doing intervals on a stationary bike is a great way to maximize your calorie burn in minimum time. Keep the intensity really high on the intervals for a couple of minutes, then slow down for a minute or so, continually repeating these intervals for as long as you can");
        db.insertOrThrow("Cardio", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Sprinting");
        newItem.put("number_of_sets", 1);
        newItem.put("reps_per_set", 1);
        newItem.put("estimate_time", 300);
        newItem.put("description", "f you’re outside on a track, try sprinting a lap and then jog a lap. Keep repeating this for as long as you can. If you’re on a treadmill, do an all-out sprint for 20-30 seconds, then slow the belt down and jog for a minute or so before repeating. At a stadium or flights of stairs? Run up to the top as fast as you can, then jog or walk down.");
        db.insertOrThrow("Cardio", null, newItem);
        newItem.clear();
        newItem.put("exercise_name", "Indoor Rowing");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Hop on an indoor rowing machine to work your entire body in ways you didn’t think were possible. Every stroke you take incorporates about 84 percent of your muscles");
        db.insertOrThrow("Cardio", null, newItem);
        newItem.clear();

        //Create workout routines and exercises
        newItem.put("workout_routine_name", "Back and Biceps");
        newItem.put("exercise_name", "Chinup");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Hang from a chinup bar with hands shoulder-width apart using a supinated grip (so, palms facing you). From the bottom of the movement, pull yourself up until your chin is over the bar.");
        db.insertOrThrow("Monday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Back and Biceps");
        newItem.put("exercise_name", "Inverted Row");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Set a barbell in a power rack (or use a Smith machine) at about hip height. (About four rungs up should work). Lie underneath it and grab it with hands about shoulder-width apart with the bottom of your heels on floor. Hang from the bar so your body forms a straight line. Squeeze your shoulder blades together and pull yourself up until your back is fully contracted.");
        db.insertOrThrow("Monday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Back and Biceps");
        newItem.put("exercise_name", "Yates Row");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Hold the bar with an underhand grip at shoulder-width. Keeping your lower back in its natural arch, bend your hips back and lower your torso to about 60 degrees. Row the weight to your belly button using a slight cheat (use momentum to begin each rep), but don’t let your lower back round. If you have wrist straps, you may use them to help your grip.");
        db.insertOrThrow("Monday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Back and Biceps");
        newItem.put("exercise_name", "Hammer Curl");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 40);
        newItem.put("description", "Select two dumbbells, and wrap towels around each handle to thicken it. Another option is to use rubber-grip sleeves like Fat Gripz or Grip4orce. Keeping your upper arms stationary at your sides and your palms facing up, curl the weights.");
        db.insertOrThrow("Monday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Back and Biceps");
        newItem.put("exercise_name", "Conventional Barbell Curl");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "You've certainly done this exercise before, but there are plenty of ways to shake up the set/rep scheme. Try this: Place three 5-lb plates on each side of the bar, hands at shoulder-width, and perform 20 reps. That’s one set. Then take off one plate from each side. Perform 30 reps. Unload another plate from each side and do 40 reps. Finally, remove the last set of plates, and do 50 reps with just the empty bar.");
        db.insertOrThrow("Monday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Leg day");
        newItem.put("exercise_name", "Front Squat");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Set a barbell on a power rack at about shoulder height. Grab the power with an overhand grip at shoulder width and raise your elbows until your upper arms are parallel to the floor. Take the bar out of the rack and let it rest on your fingertips. Your elbows should be all the way up throughout the movement. Step back and set your feet at shoulder width with toes turned out slightly. Squat as low as you can without losing the arch in your lower back.");
        db.insertOrThrow("Monday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Leg day");
        newItem.put("exercise_name", "Dumbbell Stepup");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Stand behind a bench or another elevated surface that will put your thigh at parallel to the floor when you step your foot onto it. Hold a dumbbell in each hand and step onto the bench, but leave your trailing leg hanging off.");
        db.insertOrThrow("Monday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Leg day");
        newItem.put("exercise_name", "Leg Press");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Adjust the seat of the machine so that you can sit comfortably with your hips beneath your knees and your knees in line with your feet. Remove the safeties and lower your knees toward your chest until they’re bent 90 degrees and then press back up. Be careful not to go too low or you risk your lower back coming off the seat (which can cause injury).");
        db.insertOrThrow("Monday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Leg day");
        newItem.put("exercise_name", "Barbell Calf Raise");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Place a block, step, or weight plate on the floor. Grasp a barbell and hold it on the backs of your shoulders, as in a squat. Place your toes on the block so your calves are stretched, but make sure you can maintain balance. Raise your heels to come up onto the balls of your feet.");
        db.insertOrThrow("Monday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Abdominal");
        newItem.put("exercise_name", "Running");
        newItem.put("number_of_sets", 1);
        newItem.put("reps_per_set", 1);
        newItem.put("estimate_time", 600);
        newItem.put("description", "Running at a steady, moderate pace is a sure way to burn fat and calories, but it’s not the most economical way to build or even maintain muscle.");
        db.insertOrThrow("Wednesday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Abdominal");
        newItem.put("exercise_name", "Leg Raise");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Lie on the floor and hold onto a bench or the legs of a heavy chair for support. Keep your legs straight and raise them up until they’re vertical. Lower back down, but stop just short of the floor to keep tension on your abs before the next rep.");
        db.insertOrThrow("Wednesday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Abdominal");
        newItem.put("exercise_name", "Barbell Rollout");
        newItem.put("number_of_sets", 2);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Load the bar with 10-pound plates and kneel on the floor behind it. Your shoulders should be over the bar. Brace your abs and roll the bar forward, reaching in front of you until you feel your hips are about to sag. Roll yourself back.");
        db.insertOrThrow("Wednesday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Abdominal");
        newItem.put("exercise_name", "Horizontal Cable Woodchop");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 40);
        newItem.put("description", "Set an adjustable cable pulley to shoulder level (or attach a band to a sturdy object) and grasp the handle with both hands. Stand with feet shoulder width apart, perpendicular to the anchor point, and arms extended, far enough away from the machine so there’s tension on the cable. Twist away from the machine as if you were chopping into a tree. Keep your feet stationary.");
        db.insertOrThrow("Wednesday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Chest and Triceps");
        newItem.put("exercise_name", "Barbell Bench Press");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 40);
        newItem.put("description", "Grasp the bar just outside shoulder-width and arch your back so there’s space between your lower back and the bench. Pull the bar out of the rack and lower it to your sternum, tucking your elbows about 45° to your sides. When the bar touches your body, drive your feet hard into the floor and press the bar back up.");
        db.insertOrThrow("Saturday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Chest and Triceps");
        newItem.put("exercise_name", "Incline Dumbbell Flye");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 40);
        newItem.put("description", "Set an adjustable bench to a 30°-45° angle, and lie back on it with a dumbbell in each hand. Turn your wrists so your palms face each other. Press the weights straight over your chest, then, keeping a slight bend in your elbows, spread your arms open as if you were going for a big bear hug. Lower your arms until you feel a stretch in your pecs, then bring the weights back together over your chest.");
        db.insertOrThrow("Saturday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Chest and Triceps");
        newItem.put("exercise_name", "Cable Crossover");
        newItem.put("number_of_sets", 3);
        newItem.put("reps_per_set", 10);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Stand between two facing cable stations with both pulleys set midway between the top and bottom of the station. Attach a D-handle to each pulley and hold one in each hand. Keep your elbows slightly bent, and step forward so there’s tension on the cables. Flex your pecs as you bring your hands together out in front of your chest. Alternate stretching and flexing after each set.");
        db.insertOrThrow("Saturday", null, newItem);
        newItem.clear();
        newItem.put("workout_routine_name", "Chest and Triceps");
        newItem.put("exercise_name", "Close-Grip Bench Press");
        newItem.put("number_of_sets", 4);
        newItem.put("reps_per_set", 12);
        newItem.put("estimate_time", 60);
        newItem.put("description", "Grasp the bar with your index fingers on the inside edge of the knurling (the rough part of the bar). Arch your back so there’s space between your lower back and the bench. Pull the bar off the rack and lower it to your sternum, tucking your elbows about 45° to your sides. When the bar touches your body, drive your feet hard into the floor and press the bar back up. On your last set, use half the weight and perform as many reps as possible.");
        db.insertOrThrow("Saturday", null, newItem);
        newItem.clear();

        //Create Meals
        newItem.put("meal_category_name", "Meal 1");
        newItem.put("meal_name", "3 Egg Omelet");
        newItem.put("proteins", 20);
        newItem.put("carbs", 15);
        newItem.put("fats", 32);
        newItem.put("calories", 450);
        newItem.put("description", "BEAT eggs, water, salt and pepper in small bowl until blended. HEAT butter in 7 to 10-inch nonstick omelet pan or skillet over medium-high heat until hot. TILT pan to coat bottom. POUR IN egg mixture. Mixture should set immediately at edges. GENTLY PUSH cooked portions from edges toward the center with inverted turner so that uncooked eggs can reach the hot pan surface. CONTINUE cooking, tilting pan and gently moving cooked portions as needed. When top surface of eggs is thickened and no visible liquid egg remains, PLACE filling on one side of the omelet. FOLD omelet in half with turner. With a quick flip of the wrist, turn pan and INVERT or SLIDE omelet onto plate. SERVE immediately.");
        db.insertOrThrow("MondayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 2");
        newItem.put("meal_name", "Greek Yogurt 100g");
        newItem.put("proteins", 10);
        newItem.put("carbs", 3);
        newItem.put("fats", 4);
        newItem.put("calories", 59);
        newItem.put("description", "Any greek yogurt from your grocery store");
        db.insertOrThrow("MondayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 3");
        newItem.put("meal_name", "Chocolate Cherry Smoothie 100g");
        newItem.put("proteins", 30);
        newItem.put("carbs", 30);
        newItem.put("fats", 2);
        newItem.put("calories", 140);
        newItem.put("description", "Blend 2 scoops of protein powder, coconut milk 1/4 cup, 6-8 cherries, 1tbsp flaxseeds and halt a cup of water.");
        db.insertOrThrow("MondayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 4");
        newItem.put("meal_name", "Lettuce Burger 8oz");
        newItem.put("proteins", 40);
        newItem.put("carbs", 64);
        newItem.put("fats", 48);
        newItem.put("calories", 950);
        newItem.put("description", "Fry 4 oz of ground beef meat. Once the meat is fried place it onto the lettuce leave. The cover it with sliced tomato, red onion, ketchup and mayonnaise. Place one more lettuce leave on the top and the burger is ready to be consumed.");
        db.insertOrThrow("MondayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 5");
        newItem.put("meal_name", "Single Protein bar");
        newItem.put("proteins", 15);
        newItem.put("carbs", 51);
        newItem.put("fats", 13);
        newItem.put("calories", 330);
        newItem.put("description", "Buy any protein bar from the nutrition store");
        db.insertOrThrow("MondayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 6");
        newItem.put("meal_name", "Shrimps, rice and salad 6oz");
        newItem.put("proteins", 35);
        newItem.put("carbs", 64);
        newItem.put("fats", 68);
        newItem.put("calories", 620);
        newItem.put("description", "Boil 6 large shrimps and rice. Make salad of spinach, feta cheese, bell pepper and oil. Place everything onto a single plate");
        db.insertOrThrow("MondayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 1");
        newItem.put("meal_name", "Smoothie");
        newItem.put("proteins", 35);
        newItem.put("carbs", 24);
        newItem.put("fats", 14);
        newItem.put("calories", 180);
        newItem.put("description", "Blend 1 scoop of whey protein, 300ml skimmed milk, 100g of strawberries and  banana");
        db.insertOrThrow("TuesdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 2");
        newItem.put("meal_name", "Snack");
        newItem.put("proteins", 9);
        newItem.put("carbs", 4);
        newItem.put("fats", 5);
        newItem.put("calories", 80);
        newItem.put("description", "100g mackerel on 1 slice of wholemeal toast");
        db.insertOrThrow("TuesdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 3");
        newItem.put("meal_name", "Sandwich");
        newItem.put("proteins", 22);
        newItem.put("carbs", 14);
        newItem.put("fats", 25);
        newItem.put("calories", 180);
        newItem.put("description", "Chicken salad sandwich on wholemeal bread");
        db.insertOrThrow("TuesdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 4");
        newItem.put("meal_name", "Fish steak and salad");
        newItem.put("proteins", 46);
        newItem.put("carbs", 34);
        newItem.put("fats", 25);
        newItem.put("calories", 480);
        newItem.put("description", "Fried or boiled 120g fillet steak with spinach and 2 grilled tomatoes");
        db.insertOrThrow("TuesdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 1");
        newItem.put("meal_name", "Cheesy Scrambled Egg");
        newItem.put("proteins", 24);
        newItem.put("carbs", 34);
        newItem.put("fats", 48);
        newItem.put("calories", 420);
        newItem.put("description", "Fry 4 egg whites then add cheddar cheese on the top of it. Consume with 2 slices of brown bread and scallions.");
        db.insertOrThrow("WednesdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 2");
        newItem.put("meal_name", "Glass of Milk");
        newItem.put("proteins", 6);
        newItem.put("carbs", 4);
        newItem.put("fats", 8);
        newItem.put("calories", 60);
        newItem.put("description", "Glass of cow milk");
        db.insertOrThrow("WednesdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 3");
        newItem.put("meal_name", "Blueberry Almond Smoothie");
        newItem.put("proteins", 35);
        newItem.put("carbs", 34);
        newItem.put("fats", 28);
        newItem.put("calories", 340);
        newItem.put("description", "Blend 2 scoops of protein powder, 1 cup of blueberries, 1 oz of almonds, cow milk");
        db.insertOrThrow("WednesdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 4");
        newItem.put("meal_name", " Steak with Salad");
        newItem.put("proteins", 53);
        newItem.put("carbs", 64);
        newItem.put("fats", 48);
        newItem.put("calories", 820);
        newItem.put("description", "Grill 6oz of pork steak meat. Then make salad out of cucumber, tomato, chickpeas and olive oil.");
        db.insertOrThrow("WednesdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 5");
        newItem.put("meal_name", "Protein Shake");
        newItem.put("proteins", 35);
        newItem.put("carbs", 64);
        newItem.put("fats", 68);
        newItem.put("calories", 410);
        newItem.put("description", "Blend 1 scoop of protein powder and one grass of milk.");
        db.insertOrThrow("WednesdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 6");
        newItem.put("meal_name", "Chicken with Quinoa Salad");
        newItem.put("proteins", 49);
        newItem.put("carbs", 64);
        newItem.put("fats", 68);
        newItem.put("calories", 620);
        newItem.put("description", "Bake or fry 6oz of chicken breast. Add quinoa, walnuts and craisins into 2oz of boiled watter.");
        db.insertOrThrow("WednesdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 7");
        newItem.put("meal_name", "Broccoli salad");
        newItem.put("proteins", 10);
        newItem.put("carbs", 4);
        newItem.put("fats", 18);
        newItem.put("calories", 120);
        newItem.put("description", "Boil broccoli and chop it. Add butter and cheese on the top of the hot broccoli");
        db.insertOrThrow("WednesdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 1");
        newItem.put("meal_name", "3 Egg Omelet");
        newItem.put("proteins", 20);
        newItem.put("carbs", 15);
        newItem.put("fats", 32);
        newItem.put("calories", 450);
        newItem.put("description", "BEAT eggs, water, salt and pepper in small bowl until blended. HEAT butter in 7 to 10-inch nonstick omelet pan or skillet over medium-high heat until hot. TILT pan to coat bottom. POUR IN egg mixture. Mixture should set immediately at edges. GENTLY PUSH cooked portions from edges toward the center with inverted turner so that uncooked eggs can reach the hot pan surface. CONTINUE cooking, tilting pan and gently moving cooked portions as needed. When top surface of eggs is thickened and no visible liquid egg remains, PLACE filling on one side of the omelet. FOLD omelet in half with turner. With a quick flip of the wrist, turn pan and INVERT or SLIDE omelet onto plate. SERVE immediately.");
        db.insertOrThrow("ThursdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 2");
        newItem.put("meal_name", "Greek Yogurt 100g");
        newItem.put("proteins", 10);
        newItem.put("carbs", 3);
        newItem.put("fats", 4);
        newItem.put("calories", 59);
        newItem.put("description", "");
        db.insertOrThrow("ThursdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 3");
        newItem.put("meal_name", "Chocolate Cherry Smoothie 100g");
        newItem.put("proteins", 30);
        newItem.put("carbs", 30);
        newItem.put("fats", 2);
        newItem.put("calories", 140);
        newItem.put("description", "Blend 2 scoops of protein powder, coconut milk 1/4 cup, 6-8 cherries, 1tbsp flaxseeds and halt a cup of water.");
        db.insertOrThrow("ThursdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 4");
        newItem.put("meal_name", "Lettuce Burger 8oz");
        newItem.put("proteins", 40);
        newItem.put("carbs", 64);
        newItem.put("fats", 48);
        newItem.put("calories", 950);
        newItem.put("description", "Fry 4 oz of ground beef meat. Once the meat is fried place it onto the lettuce leave. The cover it with sliced tomato, red onion, ketchup and mayonnaise. Place one more lettuce leave on the top and the burger is ready to be consumed.");
        db.insertOrThrow("ThursdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 5");
        newItem.put("meal_name", "Single Protein bar");
        newItem.put("proteins", 15);
        newItem.put("carbs", 51);
        newItem.put("fats", 13);
        newItem.put("calories", 330);
        newItem.put("description", "Buy any protein bar from the nutrition store");
        db.insertOrThrow("ThursdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 6");
        newItem.put("meal_name", "Shrimps, rice and salad 6oz");
        newItem.put("proteins", 35);
        newItem.put("carbs", 64);
        newItem.put("fats", 68);
        newItem.put("calories", 620);
        newItem.put("description", "Boil 6 large shrimps and rice. Make salad of spinach, feta cheese, bell pepper and oil. Place everything onto a single plate");
        db.insertOrThrow("ThursdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 1");
        newItem.put("meal_name", "Tomato Omelet");
        newItem.put("proteins", 30);
        newItem.put("carbs", 24);
        newItem.put("fats", 38);
        newItem.put("calories", 320);
        newItem.put("description", "Fry 3 eggs, cheese, 2 tomatos and half a garlic");
        db.insertOrThrow("FridayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 2");
        newItem.put("meal_name", "Protein shake");
        newItem.put("proteins", 30);
        newItem.put("carbs", 24);
        newItem.put("fats", 28);
        newItem.put("calories", 220);
        newItem.put("description", "Blend 1 scoop of protein powder, chocolate milk, peanut butter.");
        db.insertOrThrow("FridayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 3");
        newItem.put("meal_name", "Salmon Steak");
        newItem.put("proteins", 49);
        newItem.put("carbs", 64);
        newItem.put("fats", 68);
        newItem.put("calories", 820);
        newItem.put("description", "Baked potato and 6oz of salmon steak. 1/2 avocado and tomato salad");
        db.insertOrThrow("FridayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 4");
        newItem.put("meal_name", "Fried chicken legs");
        newItem.put("proteins", 69);
        newItem.put("carbs", 44);
        newItem.put("fats", 38);
        newItem.put("calories", 420);
        newItem.put("description", "200g of fried chicken legs and ketchup");
        db.insertOrThrow("FridayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 1");
        newItem.put("meal_name", "Spinach Omelet");
        newItem.put("proteins", 30);
        newItem.put("carbs", 24);
        newItem.put("fats", 38);
        newItem.put("calories", 320);
        newItem.put("description", "Fry 3 eggs, cheese, spinach and one peach");
        db.insertOrThrow("SaturdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 2");
        newItem.put("meal_name", "Chocolate Nut shake");
        newItem.put("proteins", 30);
        newItem.put("carbs", 24);
        newItem.put("fats", 28);
        newItem.put("calories", 220);
        newItem.put("description", "Blend 1 scoop of protein powder, chocolate milk, peanut butter.");
        db.insertOrThrow("SaturdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 3");
        newItem.put("meal_name", "Steak With Avocado-Tomato");
        newItem.put("proteins", 49);
        newItem.put("carbs", 64);
        newItem.put("fats", 68);
        newItem.put("calories", 820);
        newItem.put("description", "Baked potato and 6oz of beef steak. 1/2 avocado and tomato salad");
        db.insertOrThrow("SaturdayMeals", null, newItem);
        newItem.clear();
        newItem.put("meal_category_name", "Meal 4");
        newItem.put("meal_name", "Milk and rice");
        newItem.put("proteins", 29);
        newItem.put("carbs", 24);
        newItem.put("fats", 18);
        newItem.put("calories", 220);
        newItem.put("description", "Boil 300ml of milk. Then boil 100g of brown rice. Add rice to boiling milk plus sugarr or honey.");
        db.insertOrThrow("SaturdayMeals", null, newItem);
        newItem.clear();
    }
}